apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: python
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: adriangp/tfm-app:1.2
        imagePullPolicy: IfNotPresent
        env:
          - name: MONGO_SVC_SERVICE_HOST
            value: mongo-svc
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: python
---
apiVersion: extensions/v1beta1  
kind: Ingress  
metadata:  
  name: python
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: unir-tfm.34.76.250.116.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: app-svc
          servicePort: http